"""Apparently Chat GPT is amazing at preparing a dataset for you. ^_^"""

import random
import csv
data = [
    ("What's the weather like today?", "query"),
    ("Tell me a joke.", "chat"),
    ("How do I book a flight?", "query"),
    ("What's your name?", "chat"),
    ("Where can I find a good restaurant?", "query"),
    ("How's your day going?", "chat"),
    ("What time does the movie start?", "query"),
    ("What's your favorite color?", "chat"),
    ("How far is the nearest train station?", "query"),
    ("What did you have for breakfast?", "chat"),
    ("How tall is the Eiffel Tower?", "query"),
    ("What's your opinion on the latest news?", "chat"),
    ("What's the capital of France?", "query"),
    ("Do you like to read books?", "chat"),
    ("How long does it take to get to the airport?", "query"),
    ("What's your favorite movie?", "chat"),
    ("What's the recipe for chocolate cake?", "query"),
    ("Do you have any pets?", "chat"),
    ("What's the best way to learn a new language?", "query"),
    ("How was your weekend?", "chat"),
    # Add more examples here
    ("What's the distance between New York and Los Angeles?", "query"),
    ("Tell me about the latest technology news.", "query"),
    ("Do you enjoy listening to music?", "chat"),
    ("How do I reset my password?", "query"),
    ("What's your favorite book genre?", "chat"),
    ("What's the best way to lose weight?", "query"),
    ("How do I create a new email account?", "query"),
    ("What's your favorite type of cuisine?", "chat"),
    ("What's the best time to plant flowers?", "query"),
    ("Do you like to travel?", "chat"),
    ("How do I bake cookies from scratch?", "query"),
    ("What's your favorite hobby?", "chat"),
    ("What's the latest fashion trend?", "query"),
    ("Tell me about your favorite vacation spot.", "chat"),
    ("What's the best way to invest money?", "query"),
    ("What's your favorite TV show?", "chat"),
    ("How do I fix a leaky faucet?", "query"),
    ("What's your favorite season?", "chat"),
    ("What's the best way to learn coding?", "query"),
    ("Do you enjoy outdoor activities?", "chat"),
    ("What's the best time to go to the beach?", "query"),
    ("What's your favorite sports team?", "chat"),
    ("How do I grow tomatoes in my backyard?", "query"),
    ("What's your favorite animal?", "chat"),
    ("What's the best way to organize my closet?", "query"),
    ("What's your favorite type of music?", "chat"),
    ("How do I install a new software program?", "query"),
    ("What's your favorite holiday destination?", "chat"),
    ("What's the best way to save money?", "query"),
    ("Do you like to cook?", "chat"),
    ("How do I create a budget?", "query"),
    ("What's your favorite social media platform?", "chat"),
    ("What's the best way to study for exams?", "query"),
    ("How do I create a website?", "query"),
    ("What's your favorite type of food?", "chat"),
    ("What's the best way to stay focused while studying?", "query"),
    ("What's your favorite type of cuisine?", "chat"),
    ("How can I fix a broken zipper?", "query"),
    ("Tell me a funny joke.", "chat"),
    ("What's the fastest way to get to the nearest hospital?", "query"),
    ("How was your day today?", "chat"),
    ("What's the best way to clean a stained carpet?", "query"),
    ("Do you have any pets?", "chat"),
    ("What's the best time to water plants in hot weather?", "query"),
    ("What's your favorite book?", "chat"),
    ("How do I create a strong password?", "query"),
    ("Tell me about your favorite movie.", "chat"),
    ("What's the best way to save money for a vacation?", "query"),
    ("What's your favorite outdoor activity?", "chat"),
    ("How do I remove stains from clothes?", "query"),
    ("What's the best way to relax after a long day?", "chat"),
    ("What's the best time to go for a morning jog?", "query"),
    ("Do you enjoy cooking?", "chat"),
    ("What's your favorite type of cuisine?", "chat"),
    ("How do I plant flowers in a hanging basket?", "query"),
    ("What's your favorite hobby?", "chat"),
    ("What's the best way to clean a laptop screen?", "query"),
    ("What's your favorite TV show?", "chat"),
    ("How do I bake a perfect chocolate cake?", "query"),
    ("What's your favorite type of music?", "chat"),
    ("What's the best way to organize a messy room?", "query"),
    ("What's your favorite holiday destination?", "chat"),
    ("How do I fix a flat tire on my bike?", "query"),
    ("What's your favorite animal?", "chat"),
    ("What's the best way to de-stress after work?", "query"),
    ("Do you enjoy outdoor activities?", "chat"),
    ("What's your favorite social media platform?", "chat"),
    ("How do I tie a bowtie?", "query"),
    ("What's your favorite movie genre?", "chat"),
    ("What's the best way to stay motivated to exercise?", "query"),
    ("Do you like playing musical instruments?", "chat"),
    ("What's your favorite sports team?", "chat"),
    ("How do I create a budget for saving money?", "query"),
    ("What's your favorite season of the year?", "chat"),
    ("What's the best way to study for a math test?", "query"),
    ("Do you enjoy watching movies?", "chat"),
    ("What's your favorite type of cuisine?", "chat"),
    ("How do I fix a clogged drain in the kitchen sink?", "query"),
    ("What's your favorite holiday?", "chat"),
    ("What's the best way to improve time management skills?", "query"),
    ("Do you like to exercise?", "chat"),
    ("What's your favorite type of cuisine?", "chat"),
    ("How do I create a resume?", "query"),
    ("What's your favorite TV show?", "chat"),
    ("What's the best way to prepare for a job interview?", "query"),
    ("Do you enjoy gardening?", "chat"),
    ("What's your favorite book?", "chat"),
    ("How do I fix a broken chair?", "query"),
    ("What's your favorite outdoor activity?", "chat"),
    ("What's the best way to treat a sunburn?", "query"),
    ("Tell me about your favorite childhood memory.", "chat"),
    ("How do I bake cookies from scratch?", "query"),
    ("What's your favorite type of food?", "chat"),
    ("How do I clean a greasy stovetop?", "query"),
    ("What's your favorite color?", "chat"),
    ("What's the best way to learn a new language?", "query"),
    ("Tell me about your dream vacation destination.", "chat"),
    ("How do I create a budget for home renovation?", "query"),
    ("Do you enjoy hiking?", "chat"),
    ("What's your favorite music genre?", "chat"),
    ("How do I remove a stain from a carpet?", "query"),
    ("What's your favorite TV show?", "chat"),
    ("What's the best way to start a small business?", "query"),
    ("Do you like to dance?", "chat"),
    ("What's your favorite hobby?", "chat"),
    ("How do I fix a leaky faucet?", "query"),
    ("What's your favorite time of the day?", "chat"),
    ("What's the best way to pack for a weekend trip?", "query"),
    ("Do you enjoy camping?", "chat"),
    ("What's your favorite type of cuisine?", "chat"),
    ("How do I create a workout routine?", "query"),
    ("What's your favorite movie?", "chat"),
    ("What's the best way to prepare for a presentation?", "query"),
    ("Do you like to travel?", "chat"),
    ("What's your favorite outdoor activity?", "chat"),
    ("How do I clean a dirty microwave?", "query"),
    ("What's your favorite season of the year?", "chat"),
    ("What's the best way to deal with stress at work?", "query"),
    ("Do you enjoy painting?", "chat"),
    ("What's your favorite social media platform?", "chat"),
    ("How do I care for indoor plants?", "query"),
    ("What's your favorite sports team?", "chat"),
    ("What's the best way to improve communication skills?", "query"),
    ("Do you like to read?", "chat"),
    ("What's your favorite type of cuisine?", "chat"),
    ("How do I plan a wedding on a budget?", "query"),
    ("What's your favorite TV show?", "chat"),
    ("What's the best way to prepare for a marathon?", "query"),
    ("Do you enjoy photography?", "chat"),
    ("What's your favorite book?", "chat"),
    ("How do I fix a broken door handle?", "query"),
    ("What's your favorite outdoor activity?", "chat"),
    ("What's the best way to stay productive at work?", "query"),
    ("Do you like to cook?", "chat"),
    ("What's your favorite holiday?", "chat"),
    ("How do I clean silverware?", "query"),
    ("What's your favorite hobby?", "chat"),
    ("What's the best way to save money for retirement?", "query"),
    ("Do you enjoy playing sports?", "chat"),
    ("What's your favorite type of cuisine?", "chat"),
    ("How do I create a morning routine for a productive day?", "query"),
    ("What's your favorite movie genre?", "chat"),
    ("What's the best way to deal with difficult coworkers?", "query"),
    ("Do you like to dance?", "chat"),
    ("What's your favorite color?", "chat"),
    ("How do I repair a flat tire on my bike?", "query"),
    ("What's your favorite type of flower?", "chat"),
    ("How do I make a DIY face mask at home?", "query"),
    ("Tell me about your favorite childhood toy.", "chat"),
    ("How do I fix a leaky roof?", "query"),
    ("What's your favorite type of pet?", "chat"),
    ("How do I create a budget for a family vacation?", "query"),
    ("Do you enjoy swimming?", "chat"),
    ("What's your favorite season of the year?", "chat"),
    ("How do I remove a virus from my computer?", "query"),
    ("What's your favorite type of dessert?", "chat"),
    ("How do I build a raised garden bed?", "query"),
    ("Tell me about your favorite hiking trail.", "chat"),
    ("How do I paint a room like a pro?", "query"),
    ("What's your favorite type of weather?", "chat"),
    ("How do I fix a clogged sink drain?", "query"),
    ("Do you enjoy playing musical instruments?", "chat"),
    ("How do I start a blog from scratch?", "query"),
    ("What's your favorite type of art?", "chat"),
    ("How do I train a puppy?", "query"),
    ("Tell me about your favorite beach destination.", "chat"),
    ("How do I create a budget for buying a car?", "query"),
    ("What's your favorite type of drink?", "chat"),
    ("How do I prepare for a job interview?", "query"),
    ("Do you enjoy meditation?", "chat"),
    ("How do I sew a button on a shirt?", "query"),
    ("What's your favorite type of fashion?", "chat"),
    ("How do I organize my closet?", "query"),
    ("Tell me about your favorite camping experience.", "chat"),
    ("How do I clean a stained carpet?", "query"),
    ("What's your favorite type of exercise?", "chat"),
    ("How do I make homemade candles?", "query"),
    ("Do you enjoy doing crafts?", "chat"),
    ("How do I make a healthy smoothie?", "query"),
    ("What's your favorite type of fruit?", "chat"),
    ("How do I create a budget for buying a house?", "query"),
    ("Tell me about your favorite travel destination.", "chat"),
    ("How do I build a bookshelf?", "query"),
    ("Do you enjoy gardening?", "chat"),
    ("How do I plan a road trip?", "query"),
    ("What's your favorite type of vehicle?", "chat"),
    ("How do I clean a dirty oven?", "query"),
    ("What's your favorite type of music?", "chat"),
    ("How do I start a fitness routine?", "query"),
    ("Tell me about your favorite sports team.", "chat"),
    ("How do I fix a broken bicycle chain?", "query"),
    ("Do you enjoy watching movies?", "chat"),
    ("How do I make homemade pizza?", "query"),
    ("What's your favorite type of cuisine?", "chat"),
    ("How do I create a budget for a wedding?", "query"),
    ("Tell me about your favorite book.", "chat"),
    ("How do I paint a room with two colors?", "query"),
    ("What's your favorite type of home decor?", "chat"),
    ("How do I care for a newborn baby?", "query"),
    ("Do you enjoy parenting?", "chat"),
    ("How do I bake chocolate chip cookies from scratch?", "query"),
    ("What's your favorite type of movie genre?", "chat"),
    ("How do I write a cover letter for a job application?", "query"),
    ("Tell me about your favorite holiday destination.", "chat"),
    ("How do I fix a leaking faucet in my kitchen?", "query"),
    ("What's your favorite type of outdoor activity?", "chat"),
    ("How do I create a resume that stands out?", "query"),
    ("Do you enjoy watching sports?", "chat"),
    ("How do I tie a tie in different ways?", "query"),
    ("What's your favorite type of cuisine?", "chat"),
    ("How do I start a meditation practice?", "query"),
    ("Tell me about your favorite type of art.", "chat"),
    ("How do I create a budget for home renovation?", "query"),
    ("Do you enjoy cooking?", "chat"),
    ("How do I change a flat tire on my car?", "query"),
    ("What's your favorite type of exercise?", "chat"),
    ("How do I take care of indoor plants?", "query"),
    ("Tell me about your favorite hobby.", "chat"),
    ("How do I plan a backpacking trip?", "query"),
    ("What's your favorite type of adventure activity?", "chat"),
    ("How do I fix a broken zipper on my jacket?", "query"),
    ("Do you enjoy outdoor activities?", "chat"),
    ("How do I create a budget for retirement?", "query"),
    ("What's your favorite type of investment?", "chat"),
    ("How do I remove a stain from my carpet?", "query"),
    ("Tell me about your favorite movie.", "chat"),
    ("How do I make a budget for a small business?", "query"),
    ("Do you enjoy entrepreneurship?", "chat"),
    ("How do I create a skincare routine?", "query"),
    ("What's your favorite type of beauty product?", "chat"),
    ("How do I start a podcast?", "query"),
    ("Tell me about your favorite podcast.", "chat"),
    ("How do I fix a broken electrical outlet?", "query"),
    ("Do you enjoy DIY projects?", "chat"),
    ("How do I create a budget for education expenses?", "query"),
    ("What's your favorite type of educational content?", "chat"),
    ("How do I make homemade soap?", "query"),
    ("Tell me about your favorite TV show.", "chat"),
    ("How do I plan a wedding?", "query"),
    ("Do you enjoy event planning?", "chat"),
    ("How do I build a website from scratch?", "query"),
    ("What's your favorite type of website?", "chat"),
    ("How do I care for a pet fish?", "query"),
    ("Tell me about your favorite aquatic animal.", "chat"),
    ("How do I fix a leaking roof?", "query"),
    ("Do you enjoy home improvement projects?", "chat"),
    ("How do I create a budget for a family vacation?", "query"),
    ("What's your favorite type of vacation destination?", "chat"),
    ("How do I start a blog?", "query"),
    ("Tell me about your favorite blog.", "chat"),
    ("How do I fix a broken smartphone screen?", "query"),
    ("Do you enjoy using technology?", "chat"),
    ("How do I create a budget for a fitness routine?", "query"),
    ("What's your favorite type of fitness activity?", "chat"),
    ("How do I create a budget for a road trip?", "query"),
    ("What's your favorite type of road trip destination?", "chat"),
    ("How do I fix a leaking toilet?", "query"),
    ("Do you enjoy DIY plumbing projects?", "chat"),
    ("How do I create a budget for a home gym?", "query"),
    ("What's your favorite type of exercise equipment?", "chat"),
    ("How do I write a short story?", "query"),
    ("Tell me about your favorite book.", "chat"),
    ("How do I create a budget for a hiking trip?", "query"),
    ("Do you enjoy hiking?", "chat"),
    ("How do I sew a button on a shirt?", "query"),
    ("What's your favorite type of fabric?", "chat"),
    ("How do I create a budget for a photography hobby?", "query"),
    ("Tell me about your favorite photography subject.", "chat"),
    ("How do I change a car battery?", "query"),
    ("Do you enjoy automotive repairs?", "chat"),
    ("How do I create a budget for a home office setup?", "query"),
    ("What's your favorite type of office furniture?", "chat"),
    ("How do I cook a perfect steak?", "query"),
    ("What's your favorite type of steak?", "chat"),
    ("How do I create a budget for a gardening project?", "query"),
    ("Do you enjoy gardening?", "chat"),
    ("How do I fix a leaky faucet in my bathroom?", "query"),
    ("What's your favorite type of bathroom fixture?", "chat"),
    ("How do I create a budget for a painting project?", "query"),
    ("Tell me about your favorite type of painting.", "chat"),
    ("How do I unclog a kitchen sink?", "query"),
    ("Do you enjoy DIY plumbing repairs?", "chat"),
    ("How do I create a budget for a home decor project?", "query"),
    ("What's your favorite type of home decor?", "chat"),
    ("How do I install a ceiling fan?", "query"),
    ("Do you enjoy home improvement projects?", "chat"),
    ("How do I create a budget for a camping trip?", "query"),
    ("What's your favorite type of camping experience?", "chat"),
    ("How do I paint a room?", "query"),
    ("Tell me about your favorite color.", "chat"),
    ("How do I create a budget for a car maintenance?", "query"),
    ("Do you enjoy automotive maintenance?", "chat"),
    ("How do I create a budget for a travel adventure?", "query"),
    ("What's your favorite type of travel adventure?", "chat"),
    ("How do I repair a leaky roof?", "query"),
    ("Do you enjoy DIY roofing projects?", "chat"),
    ("How do I create a budget for a home renovation?", "query"),
    ("Tell me about your favorite room in a house.", "chat"),
    ("How do I fix a broken window?", "query"),
    ("Do you enjoy DIY window repairs?", "chat"),
    ("How do I create a budget for a fitness challenge?", "query"),
    ("What's your favorite type of fitness challenge?", "chat"),
    ("How do I make homemade candles?", "query"),
    ("Tell me about your favorite candle scent.", "chat"),
    ("How do I create a budget for a language learning course?", "query"),
    ("Do you enjoy learning new languages?", "chat"),
    ("How do I install a security camera?", "query"),
    ("How do I create a budget for a road trip?", "query"),
    ("What's your favorite type of road trip destination?", "chat"),
    ("What's the value of pi?", "query"),
    ("What's the weather like today?", "query"),
    ("Tell me a joke!", "chat"),
    ("How do I bake cookies from scratch?", "query"),
    ("What's your favorite book?", "chat"),
    ("How to grow tomatoes in a garden?", "query"),
    ("Do you have any pets?", "chat"),
    ("How to tie a bow tie?", "query"),
    ("What's your favorite movie?", "chat"),
    ("Play some music.", "query"),
    ("Cut the call.", "query"),
    ("Shut down the system.", "query"),
    ("Open the window.", "query"),
    ("Turn off the lights.", "query"),
    ("Set a reminder for tomorrow.", "query"),
    ("Check my email.", "query"),
    ("Book a flight to New York.", "query"),
    ("Add milk to my shopping list.", "query"),
    ("Take a photo.", "query"),
    ("Send a message to John.", "query"),
    ("Call mom.", "query"),
    ("Play some music.", "query"),
    ("Stop the video.", "query"),
    ("Increase the volume.", "query"),
    ("Open the door.", "query"),
    ("Close the window.", "query"),
    ("Set a timer for 10 minutes.", "query"),
    ("Search for a nearby restaurant.", "query"),
    ("Turn on the TV.", "query"),
    ("Find directions to the nearest gas station.", "query"),
    ("Print the document.", "query"),
    ("Lock the screen.", "query"),
    ("Take a screenshot.", "query"),
    ("Send a text message to Jane.", "query"),
    ("Add eggs to my grocery list.", "query"),
    ("Turn off the oven.", "query"),
    ("Call a taxi.", "query"),
    ("Clear my browsing history.", "query"),
    ("Restart the computer.", "query"),
    ("Order a pizza.", "query"),
    ("Delete all spam emails.", "query"),
    ("Navigate to the nearest pharmacy.", "query"),
    ("Check my calendar.", "query"),
    ("Play my favorite playlist.", "query"),
    ("Turn off the lights.", "query"),
    ("Order a book online.", "query"),
    ("Create a new folder.", "query"),
    ("Check the weather forecast.", "query"),
    ("Set an alarm for 7 a.m.", "query"),
    ("Delete all files in the trash.", "query"),
    ("Play the latest news.", "query"),
    ("Schedule a meeting for tomorrow.", "query"),
    ("Send an email to John.", "query"),
    ("Search for a recipe.", "query"),
    ("Adjust the thermostat to 68°F.", "query"),
    ("Share the document with team members.", "query"),
    ("Turn on the fan.", "query"),
    ("Add an event to my calendar.", "query"),
    ("Archive all old emails.", "query"),
    ("Check stock prices.", "query"),
    ("Start a video call.", "query"),
    ("Set a reminder to call mom.", "query"),
    ("Post a status update on social media.", "query"),
    ("Rename a file.", "query"),
    ("Translate a sentence.", "query"),
    ("Calculate the tip.", "query"),
    ("Find a nearby hotel.", "query"),
    ("Search for the capital of France.", "query"),
    ("Find the release date of a movie.", "query"),
    ("What is the population of New York City?", "query"),
    ("Look up the definition of 'serendipity'.", "query"),
    ("Search for the latest news about climate change.", "query"),
    ("Find the nearest coffee shop.", "query"),
    ("Look up the nutritional value of an apple.", "query"),
    ("What are the symptoms of the common cold?", "query"),
    ("Search for famous landmarks in Rome.", "query"),
    ("Find the current time in Tokyo.", "query"),
    ("What are the ingredients for making lasagna?", "query"),
    ("Search for the history of the Great Wall of China.", "query"),
    ("Find the average temperature in Miami in July.", "query"),
    ("Look up the lyrics of a song.", "query"),
    ("What is the capital of Australia?", "query"),
    ("Search for the best hiking trails in Yosemite National Park.", "query"),
    ("Find information about a historical figure.", "query"),
    ("Look up a recipe for chocolate chip cookies.", "query"),
    ("What is the lifespan of a butterfly?", "query"),
    ("Search for famous paintings by Vincent van Gogh.", "query"),
    ("Find the distance between two cities.", "query"),
    ("Look up the definition of a scientific term.", "query"),
    ("Search for the latest sports scores.", "query"),
    ("Search for the best restaurant near me.", "query"),
    ("Find the latest stock prices of Apple Inc.", "query"),
    ("What is the tallest mountain in the world?", "query"),
    ("Look up the weather forecast for tomorrow.", "query"),
    ("Search for the biography of a famous person.", "query"),
    ("Find information about a specific book or author.", "query"),
    ("What is the capital of Brazil?", "query"),
    ("Look up the definition of a technical term.", "query"),
    ("Search for the latest technology news.", "query"),
    ("Find the release date of a new album.", "query"),
    ("What are the steps to bake a chocolate cake?", "query"),
    ("Search for the meaning of a foreign word.", "query"),
    ("Look up the symptoms of a particular disease.", "query"),
    ("Find the latest fashion trends.", "query"),
    ("What are the rules of a particular sport?", "query"),
    ("Search for the latest movie reviews.", "query"),
    ("Find information about a famous landmark.", "query"),
    ("Look up the details of a scientific experiment.", "query"),
    ("Search for the best travel destinations for summer.", "query"),
    ("Find the nutritional value of a specific food item.", "query"),
    ("What is the current exchange rate between two currencies?", "query"),
    ("Search for the history of a particular event.", "query"),
    ("Look up the lyrics of a song in a different language.", "query"),
    ("Find information about a famous invention or discovery.", "query"),
    ("Hello!", "chat"),
    ("Hi there!", "chat"),
    ("How are you?", "chat"),
    ("What's up?", "chat"),
    ("Good morning!", "chat"),
    ("Good afternoon!", "chat"),
    ("Good evening!", "chat"),
    ("Hey!", "chat"),
    ("Nice to meet you.", "chat"),
    ("How's your day going?", "chat"),
    ("What are you doing?", "chat"),
    ("Tell me a joke.", "chat"),
    ("Share something interesting.", "chat"),
    ("Do you have any hobbies?", "chat"),
    ("What's your favorite color?", "chat"),
    ("How old are you?", "chat"),
    ("What's your name?", "chat"),
    ("What's the meaning of life?", "chat"),
    ("How do you do?", "chat"),
    ("How's the weather today?", "chat"),
    ("Have you seen any good movies lately?", "chat"),
    ("What's your opinion on a current event?", "chat"),
    ("How's your day been?", "chat"),
    ("What's new?", "chat"),
    ("Tell me about yourself.", "chat"),
    ("How was your weekend?", "chat"),
    ("What do you do for fun?", "chat"),
    ("Do you like to travel?", "chat"),
    ("What's your favorite food?", "chat"),
    ("Do you have any pets?", "chat"),
    ("What's your favorite book?", "chat"),
    ("Do you like sports?", "chat"),
    ("What's your favorite TV show?", "chat"),
    ("What are your plans for the day?", "chat"),
    ("How's your week been so far?", "chat"),
    ("Tell me about your interests.", "chat"),
    ("Do you have any siblings?", "chat"),
    ("What's your favorite hobby?", "chat"),
    ("Tell me about your day.", "chat"),
    ("What's your favorite movie?", "chat"),
    ("Do you like to cook?", "chat"),
    ("What are your favorite pastimes?", "chat"),
    ("How's the weather today?", "chat"),
    ("Did you watch any movies recently?", "chat"),
    ("What's your favorite color?", "chat"),
    ("Tell me a joke.", "chat"),
    ("Do you like to read?", "chat"),
    ("What's your favorite season?", "chat"),
    ("Do you enjoy listening to music?", "chat"),
    ("What's your favorite holiday?", "chat"),
    ("Tell me something interesting.", "chat"),
    ("Do you like to travel?", "chat"),
    ("What's your favorite time of day?", "chat"),
    ("Do you like to exercise?", "chat"),
    ("What's your favorite type of cuisine?", "chat"),
    ("Tell me about your dreams.", "chat"),
    ("Do you like to shop?", "chat"),
    ("What's your favorite place you've visited?", "chat"),
    ("Tell me about your hometown.", "chat"),
    ("Do you like to watch TV shows?", "chat"),
    ("What's your favorite animal?", "chat"),
    ("Tell me about your favorite childhood memory.", "chat")]

# Shuffle the data
random.shuffle(data)

# Define proportions for train, test, and validation datasets
train_proportion = 0.7
test_proportion = 0.15
valid_proportion = 0.15

# Calculate number of examples for each dataset
num_examples = len(data)
num_train = int(train_proportion * num_examples)
num_test = int(test_proportion * num_examples)
num_valid = int(valid_proportion * num_examples)

# Split the data into train, test, and validation datasets
train_data = data[:num_train]
test_data = data[num_train:num_train+num_test]
valid_data = data[num_train+num_test:]

# Save train dataset to CSV
with open('train_data.csv', mode='w', newline='', encoding='utf-8-sig') as file:
    writer = csv.writer(file)
    writer.writerow(['text', 'label'])
    writer.writerows(train_data)

# Save test dataset to CSV
with open('test_data.csv', mode='w', newline='', encoding='utf-8-sig') as file:
    writer = csv.writer(file)
    writer.writerow(['text', 'label'])
    writer.writerows(test_data)

# Save validation dataset to CSV
with open('valid_data.csv', mode='w', newline='', encoding='utf-8-sig') as file:
    writer = csv.writer(file)
    writer.writerow(['text', 'label'])
    writer.writerows(valid_data)
    